---
- name: Wake Desktop
  hosts: localhost
  connection: local
  tasks:
    - name: Run Wake-on-LAN script
      command: /usr/local/bin/wake-desktop
      register: result
      changed_when: result.rc == 0
    
    - name: Show output
      debug:
        msg: "{{ result.stdout }}"
