---
- name: Restart Sunshine
  systemd:
    name: sunshine
    state: restarted
    scope: user
  become: yes
  become_user: "{{ sunshine_user }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ ansible_user_uid }}"

- name: Update Grub
  command: update-grub
  become: yes

- name: Reload udev
  command: udevadm control --reload-rules && udevadm trigger
  become: yes
