---
- name: Reload udev
- name: Reload udev
  shell: udevadm control --reload-rules && udevadm trigger
  
- name: Restart Sunshine
  command: systemctl --user restart sunshine
  become: yes
  become_user: "{{ sunshine_user }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ sunshine_uid.stdout }}"

- name: Reload systemd user daemon
  command: systemctl --user daemon-reload
  become: yes
  become_user: "{{ sunshine_user }}"
  environment:
    XDG_RUNTIME_DIR: "/run/user/{{ sunshine_uid.stdout }}"

- name: Update Grub
  command: update-grub

- name: Restart GDM
  service:
    name: gdm3
    state: restarted
