tailscale_auth_key: ENC[AES256_GCM,data:Rn99EyZYyjIu1p3pNk+USSQEjF+ZjEljbreeSuipKaAOXRNlAARohd/xgVJxITNra4uSOmAP9XA6dJ57hg==,iv:AdowcwKvc1xORCSUxMIYkHW7fTqvQcw6rIhqf4xjN/g=,tag:C2lPJN+0VZ17abYytsFnoA==,type:str]
github_runner_token: ENC[AES256_GCM,data:IYSWVtHTz3dG8KZ7qdfDQmDipxpNXBEg1dYRIDs=,iv:JfmitjzynOwWMKXFV6XjeioRLgBSSxKxiHWS969Kf9s=,tag:Rk469Vir+/o/qzOefl5ojw==,type:str]
desktop_mac_address: ENC[AES256_GCM,data:h3bY870QXq3uO4o58BCBJoU=,iv:awv1NpKVIMFwNQWxzsDSe+cNqjUO+sowEG/oUZGGddg=,tag:jrTPi3q3U+voQ9/A+UDQ0Q==,type:str]
sops:
    age:
        - recipient: age1gpgdca2u5x7gtderh9hux5fgkt8nrt7k4u5rumhrjzd8sjt86gss3qcxgn
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkSVVpL0JldWNZWU13VzB0
            K0FteGdONTRBTG13ditjUm5xSVFqL3dKWkMwClgvSVozd3F6aTNYV1ExN1VkcUp6
            UDR5VEZRek1MVlRGOStJTVlCT3QzQ2cKLS0tIDBGeVlZM3JyR1VQS2hocEgvWHBq
            NVNNWTE3NXE1T3lpRzAwQzQwYUdBbGcKhCZh+bzsmSi7mS0kvnwbxSfSPXLo2/WA
            8GcEE7abZcnyCXjmuHYvHaUaHsy4upSqfEinkQgTRbZDrIlESlADBg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-19T06:04:01Z"
    mac: ENC[AES256_GCM,data:WWRXaXyjsmaZcgXvCj1oQ1R4bfYnFtImxRx9Jj88lg5sWwPjbcNq8K2sTFObqG5erSIV6MfPuudCyb5/CnQJPEkvtl9W0LsGMXaUu5D7Hm/j4tWgKUN4kRQlCTzH/ATgNXoNlA6KR9qDVZ2cHtr4Q+3t6F47zTp9dkEu88IkKDQ=,iv:Sv2Tkt7Xv+HnwKljmpvmFMIVSikDX4npTPmOA4bzVEE=,tag:wVvomFmqN+6aaH8rm90PDg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
